# Generated by Django 2.2.28 on 2023-01-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221201_0117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_create',
        ),
    ]
